name: Plant a tree on every push to main
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Plant a Tree
        id: planttree
        uses: tjarkdoering/continuous-reforestation@main
        with:
        # Enter your API variables below
            apikey: ${{ secrets.raaskey }}
            enterpriseid: "cd7cedcd"
            user: ${{ github.actor }}
            treecount: 1
            projectid: "14442771" # This projectid can be used to have your trees planted where they are needed the most, so this is a great ID to use by default when making the API call. 
            production: "true"

      - name: Response of digitalhumani.com RaaS API
        run: |
            echo "${{ steps.planttree.outputs.response }}"
            echo "${{ steps.planttree.outputs.plantedTrees }}"

      - name: Create a badge with the number of trees planted
            uses: RubbaBoy/BYOB@v1.2.0
            with:
                NAME: treebadge
                LABEL: 'Trees planted:'
                STATUS: ${{ steps.planttree.outputs.plantedTrees }}
                COLOR: 40bc42
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
